image: node:9.8

pages:
  script:
    - apt-get -y update
    - apt install -y python3 python3-pip python3-wheel
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - cp public/bin/renomtag-*.tar.gz public/bin/renomtag_latest.tar.gz
    - cp public/bin/renomtag-*.whl public/bin/renomtag_latest.whl
#    - mkdir sdist
#    - tar xzf dist/*.tar.gz -C sdist
#    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
#    - chmod +x Miniconda3-latest-Linux-x86_64.sh
#    - ./Miniconda3-latest-Linux-x86_64.sh -b -p miniconda
#    - miniconda/bin/conda install -y conda-build
#    - miniconda/bin/conda config --add channels conda-forge
#    - miniconda/bin/conda-build conda
#    - mv miniconda/conda-bld/linux-64/renomtag-* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  only:
    - master
