image: node:10.15

before_script:
  - apt-get -y update
  - apt install -y python3 python3-pip python3-wheel
  - pip3 install -r requirements.txt

test:
  script:
    - pip3 install -e .
    - pytest
    - cd js
    - npm install
    - npm run unit
    - cd ..

pages:
  script:
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
#    - mkdir sdist
#    - tar xzf dist/*.tar.gz -C sdist
#    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
#    - chmod +x Miniconda3-latest-Linux-x86_64.sh
#    - ./Miniconda3-latest-Linux-x86_64.sh -b -p miniconda
#    - miniconda/bin/conda install -y conda-build
#    - miniconda/bin/conda config --add channels conda-forge
#    - miniconda/bin/conda-build conda
#    - mv miniconda/conda-bld/linux-64/renom_tag-* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  only:
    - /^release\/.*$/
