package:
  name: renom_tag
  version: 0.0.1

source:
  path: ../sdist/renom_tag-0.0.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - beautifulsoup4
    - bottle
    - glob2
    - lxml
    - pillow
    - pyyaml
    - watchdog
    - xmltodict
